kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:9092
      kafkaConnect:
        - name: worker-1
          address: http://localhost:8083
      ksqldbServer: http://localhost:8088
      schemaRegistry: http://localhost:8081